version: "3.5"

services:
  public-service:
    image: localhost/adidas-be-challenge-publicservice:latest
    container_name: adidas-be-challenge-publicservice
    build:
      context: public-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
      - private-network
    links:
      - "priority-sale-service"

  priority-sale-service:
    image: localhost/adidas-be-challenge-prioritysaleservice:latest
    container_name: adidas-be-challenge-prioritysaleservice
    build:
      context: priority-sale-service
      dockerfile: Dockerfile
    networks:
      - keycloak-network
      - private-network
    links:
      - "adi-club-service"
      - "email-service"

  adi-club-service:
    image: localhost/adidas-be-challenge-adiclubservice:latest
    container_name: adidas-be-challenge-adiclubservice
    build:
      context: adiclub-service
      dockerfile: Dockerfile
    networks:
      - private-network

  email-service:
    image: localhost/adidas-be-challenge-emailservice:latest
    container_name: adidas-be-challenge-emailservice
    build:
      context: email-service
      dockerfile: Dockerfile
    networks:
      - private-network

  keycloak:
    image: jboss/keycloak:16.0.0 # NOTE: Custom image build working on Mac M1 (https://github.com/docker/for-mac/issues/5310)
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "10000:8080"
    restart: unless-stopped
    networks:
      - keycloak-network
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:14.1-alpine
    container_name: keycloak-db
    restart: always
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    networks:
      - keycloak-network
    volumes:
      - keycloak-db:/var/lib/postgresql/data

networks:
  keycloak-network:
  private-network:

volumes:
  keycloak-db:
    driver:
      local
