version: "3.5"

services:
  public-service:
    image: localhost/adidas-be-challenge-publicservice:latest
    container_name: adidas-be-challenge-publicservice
    build:
      context: public-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - private-network
    environment:
      - KEYCLOAK_REALM_URI=http://keycloak:8080/auth/realms/adidas
      - ADICLUB_SERVICE_URI=adidas-be-challenge-adiclubservice
      - PRIORITY_SALE_SERVICE_URI=adidas-be-challenge-prioritysaleservice
      - EMAIL_SERVICE_URI=adidas-be-challenge-emailservice
    depends_on:
      - keycloak
      - priority-sale-service
      - adi-club-service
      - email-service

  priority-sale-service:
    image: localhost/adidas-be-challenge-prioritysaleservice:latest
    container_name: adidas-be-challenge-prioritysaleservice
    build:
      context: priority-sale-service
      dockerfile: Dockerfile
    networks:
      - private-network
    environment:
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/auth/realms/adidas/protocol/openid-connect/token
      - GATEWAY_URI=adidas-be-challenge-publicservice
      - PRIORITY_SALE_CLIENT_ID=${PRIORITY_SALE_CLIENT_ID}
      - PRIORITY_SALE_CLIENT_SECRET=${PRIORITY_SALE_CLIENT_SECRET}
    depends_on:
      - keycloak

  adi-club-service:
    image: localhost/adidas-be-challenge-adiclubservice:latest
    container_name: adidas-be-challenge-adiclubservice
    build:
      context: adiclub-service
      dockerfile: Dockerfile
    networks:
      - private-network
    depends_on:
      - keycloak

  email-service:
    image: localhost/adidas-be-challenge-emailservice:latest
    container_name: adidas-be-challenge-emailservice
    build:
      context: email-service
      dockerfile: Dockerfile
    networks:
      - private-network
    depends_on:
      - keycloak

  keycloak:
    image: jboss/keycloak:16.0.0 # NOTE: Custom image build working on Mac M1 (https://github.com/docker/for-mac/issues/5310)
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "10000:8080"
    restart: unless-stopped
    networks:
      - private-network
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:14.1-alpine
    container_name: keycloak-db
    restart: always
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    networks:
      - private-network
    volumes:
      - keycloak-db:/var/lib/postgresql/data

networks:
  private-network:

volumes:
  keycloak-db:
    driver:
      local
