server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          priority-sale-service:
            client-id: ${PRIORITY_SALE_CLIENT_ID:internal-service}
            client-secret: ${PRIORITY_SALE_CLIENT_SECRET:jlsUQA4iHDem2hTd4YFJ6RxOk7LVVZBH}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          priority-sale-service:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:10000/auth/realms/adidas/protocol/openid-connect/token}

adiclub:
  endpoint: http://${GATEWAY_URI:localhost}:8080/adiclub
  search:
    endpoint: /search

email:
  endpoint: http://${GATEWAY_URI:localhost}:8080/email
  send:
    endpoint: /notifications
