spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:
        - id: adiclub-service
          uri: http://localhost:8081
          predicates:
            - Path=/adiclub/**
        - id: priority-sale-service
          uri: http://localhost:8082
          predicates:
            - Path=/priority-sale/**

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE