spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:
        - id: adiclub-service
          uri: http://${ADICLUB_SERVICE_URI:localhost}:8081
          predicates:
            - Path=/adiclub/**
        - id: priority-sale-service
          uri: http://${PRIORITY_SALE_SERVICE_URI:localhost}:8082
          predicates:
            - Path=/priority-sale/**
        - id: email-service
          uri: http://${EMAIL_SERVICE_URI:localhost}:8083
          predicates:
            - Path=/email/**
        - id: priority-sale-service-api-docs
          uri: http://${PRIORITY_SALE_SERVICE_URI:localhost}:8082
          predicates:
            - Path=/v3/api-docs/**
        - id: priority-sale-service-swagger-ui
          uri: http://${PRIORITY_SALE_SERVICE_URI:localhost}:8082
          predicates:
            - Path=/swagger-ui/**,/swagger-ui.html,/webjars/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:10000/auth/realms/adidas}
          jwk-set-uri: ${KEYCLOAK_REALM_URI:http://localhost:10000/auth/realms/adidas}/protocol/openid-connect/certs

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
