spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:
        - id: adiclub-service
          uri: http://localhost:8081
          predicates:
            - Path=/adiclub/**
        - id: priority-sale-service
          uri: http://localhost:8082
          predicates:
            - Path=/priority-sale/**
        - id: email-service
          uri: http://localhost:8083
          predicates:
            - Path=/email/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:10000/auth/realms/dev}
          jwk-set-uri: ${KEYCLOAK_REALM_URL:http://localhost:10000/auth/realms/dev}/protocol/openid-connect/certs

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: TRACE
