name: Upload artifacts to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-artifacts:
    name: build-artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Make envfile for public-service
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_KEYCLOAK_REALM_URI: ${{ secrets.KEYCLOAK_REALM_URI }}
          envkey_ADICLUB_SERVICE_URI: ${{ secrets.ADICLUB_SERVICE_URI }}
          envkey_PRIORITY_SALE_SERVICE_URI: ${{ secrets.PRIORITY_SALE_SERVICE_URI}}
          envkey_EMAIL_SERVICE_URI: ${{ secrets.EMAIL_SERVICE_URI }}
          directory: public-service
          file_name: .env

      - name: Make envfile for priority-sale-service
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_KEYCLOAK_TOKEN_URI: ${{ secrets.KEYCLOAK_TOKEN_URI}}
          envkey_GATEWAY_URI: ${{ secrets.GATEWAY_URI }}
          envkey_PRIORITY_SALE_CLIENT_ID: ${{ secrets.PRIORITY_SALE_CLIENT_ID }}
          envkey_PRIORITY_SALE_CLIENT_SECRET: ${{ secrets.PRIORITY_SALE_CLIENT_SECRET }}
          directory: priority-sale-service
          file_name: .env

      - name: Upload public-service artifact
        uses: actions/upload-artifact@v2
        with:
          path: public-service/target
          name: public-service.jar

      - name: Upload priority-sale-service artifact
        uses: actions/upload-artifact@v2
        with:
          path: priority-sale-service/target
          name: priority-sale-service.jar

      - name: Upload adiclub-service artifact
        uses: actions/upload-artifact@v2
        with:
          path: adiclub-service/target
          name: adiclub-service.jar

      - name: Upload email-service artifact
        uses: actions/upload-artifact@v2
        with:
          path: email-service/target
          name: email-service.jar

  upload-artifacts:
    name: upload-artifacts
    runs-on: ubuntu-latest
    needs: build-artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download public-service artifact
        uses: actions/download-artifact@v2
        with:
          name: public-service.jar
          path: target

      - name: Download priority-sale-service artifact
        uses: actions/download-artifact@v2
        with:
          name: priority-sale-service.jar
          path: target

      - name: Download adiclub-service artifact
        uses: actions/download-artifact@v2
        with:
          name: adiclub-service.jar
          path: target

      - name: Download email-service artifact
        uses: actions/download-artifact@v2
        with:
          name: email-service.jar
          path: target

      - name: Upload public-service Docker image
        uses: docker/build-push-action@v1
        with:
          repository: adrianlzgi/adidas-java-coding-challenge-2022
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: public-service
          push: true
          dockerfile: ./public-service/Dockerfile

      - name: Upload priority-sale-service Docker image
        uses: docker/build-push-action@v1
        with:
          repository: adrianlzgi/adidas-java-coding-challenge-2022
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: priority-sale-service
          push: true
          dockerfile: ./priority-sale-service/Dockerfile

      - name: Upload adiclub-service Docker image
        uses: docker/build-push-action@v1
        with:
          repository: adrianlzgi/adidas-java-coding-challenge-2022
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: adiclub-service
          push: true
          dockerfile: ./adiclub-service/Dockerfile

      - name: Upload email-service Docker image
        uses: docker/build-push-action@v1
        with:
          repository: adrianlzgi/adidas-java-coding-challenge-2022
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: email-service
          push: true
          dockerfile: ./email-service/Dockerfile
